#!/usr/bin/perl

use strict;
use Term::ANSIColorx::ColorNicknames;
use Term::ANSIColorx::AutoFilterFH qw(filtered_handle);
use Getopt::Long;

my $truncate;
Getopt::Long::Configure("bundling"); # make switches case sensitive (and turn on bundling)
GetOptions(
    "help|h"    => sub { pod2usage(-verbose=>1) },
    "trunc|t=i" => \$truncate, # whether to truncate the line
);

my $newstdout = filtered_handle(\*STDOUT, @ARGV);
$| = 1; my $oldstdout = select $newstdout; $|=1;
$newstdout->set_truncate($truncate) if $truncate;

while(<STDIN>) {
    print
}
