#!/usr/bin/perl

use strict;
use Term::ANSIColorx::AutoFilterFH qw(filtered_handle);

my $newstdout = filtered_handle(\*STDOUT, @ARGV);
$| = 1; my $oldstdout = select $newstdout; $|=1;
print while <STDIN>;
